// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project.Data;

#nullable disable

namespace project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260104130835_AddIsAdminToUser")]
    partial class AddIsAdminToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("project.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<string>("SpecialRequests")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TravelPackageId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TravelPackageId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("project.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<DateTime>("SelectedEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SelectedStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialRequests")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TravelPackageId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TravelPackageId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("project.Models.TravelPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DefaultEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DefaultStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TravelPackages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultEndDate = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultStartDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Philosopher's Path Walk",
                            Destination = "Kyoto, Japan",
                            DurationDays = 14,
                            ImageUrl = "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=2070&auto=format&fit=crop",
                            IsActive = true,
                            Price = 4200m,
                            Season = "spring"
                        },
                        new
                        {
                            Id = 2,
                            DefaultEndDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultStartDate = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Private Tulip Fields Tour",
                            Destination = "Keukenhof, Holland",
                            DurationDays = 15,
                            ImageUrl = "https://images.unsplash.com/photo-1460500063983-994d4c27756c?q=80&w=2070&auto=format&fit=crop",
                            IsActive = true,
                            Price = 3100m,
                            Season = "spring"
                        },
                        new
                        {
                            Id = 3,
                            DefaultEndDate = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultStartDate = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Austral Spring Trek",
                            Destination = "Patagonia, Chile",
                            DurationDays = 15,
                            ImageUrl = "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=2070&auto=format&fit=crop",
                            IsActive = true,
                            Price = 5800m,
                            Season = "spring"
                        },
                        new
                        {
                            Id = 4,
                            DefaultEndDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultStartDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Private Yacht Charter",
                            Destination = "Amalfi Coast, Italy",
                            DurationDays = 15,
                            ImageUrl = "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?q=80&w=2560&auto=format&fit=crop",
                            IsActive = true,
                            Price = 6500m,
                            Season = "summer"
                        },
                        new
                        {
                            Id = 5,
                            DefaultEndDate = new DateTime(2025, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultStartDate = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Caldera Sunset Villas",
                            Destination = "Santorini, Greece",
                            DurationDays = 15,
                            ImageUrl = "https://images.unsplash.com/photo-1601581875309-fafbf2d3ed2a?q=80&w=2574&auto=format&fit=crop",
                            IsActive = true,
                            Price = 5200m,
                            Season = "summer"
                        },
                        new
                        {
                            Id = 6,
                            DefaultEndDate = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultStartDate = new DateTime(2025, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Overwater Sanctuary",
                            Destination = "Baa Atoll, Maldives",
                            DurationDays = 10,
                            ImageUrl = "https://images.unsplash.com/photo-1540206351-d6465b3ac5c1?q=80&w=2664&auto=format&fit=crop",
                            IsActive = true,
                            Price = 8900m,
                            Season = "summer"
                        },
                        new
                        {
                            Id = 7,
                            DefaultEndDate = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultStartDate = new DateTime(2025, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "New England Foliage Tour",
                            Destination = "Vermont, USA",
                            DurationDays = 15,
                            ImageUrl = "https://images.unsplash.com/photo-1509565840034-3c385bbe6451?q=80&w=2000&auto=format&fit=crop",
                            IsActive = true,
                            Price = 3800m,
                            Season = "autumn"
                        },
                        new
                        {
                            Id = 8,
                            DefaultEndDate = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultStartDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Castle & Forest Route",
                            Destination = "Bavaria, Germany",
                            DurationDays = 14,
                            ImageUrl = "https://images.unsplash.com/photo-1505307469735-373801f95c47?q=80&w=2670&auto=format&fit=crop",
                            IsActive = true,
                            Price = 4500m,
                            Season = "autumn"
                        },
                        new
                        {
                            Id = 9,
                            DefaultEndDate = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultStartDate = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Momiji Maple Viewing",
                            Destination = "Arashiyama, Japan",
                            DurationDays = 15,
                            ImageUrl = "https://images.unsplash.com/photo-1476611317561-60e1b778edfb?q=80&w=2670&auto=format&fit=crop",
                            IsActive = true,
                            Price = 4800m,
                            Season = "autumn"
                        },
                        new
                        {
                            Id = 10,
                            DefaultEndDate = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultStartDate = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Aurora Glass Igloos",
                            Destination = "Lapland, Finland",
                            DurationDays = 26,
                            ImageUrl = "https://images.unsplash.com/photo-1518182170546-0766ce6fec56?q=80&w=2000&auto=format&fit=crop",
                            IsActive = true,
                            Price = 5500m,
                            Season = "winter"
                        },
                        new
                        {
                            Id = 11,
                            DefaultEndDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultStartDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Matterhorn Ski Chalet",
                            Destination = "Zermatt, Switzerland",
                            DurationDays = 26,
                            ImageUrl = "https://images.unsplash.com/photo-1551524357-1249fa6b2eb1?q=80&w=2670&auto=format&fit=crop",
                            IsActive = true,
                            Price = 7200m,
                            Season = "winter"
                        },
                        new
                        {
                            Id = 12,
                            DefaultEndDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultStartDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Luxury Winter Retreat",
                            Destination = "Aspen, USA",
                            DurationDays = 13,
                            ImageUrl = "https://images.unsplash.com/photo-1518096366620-33062d35508a?q=80&w=2670&auto=format&fit=crop",
                            IsActive = true,
                            Price = 9500m,
                            Season = "winter"
                        });
                });

            modelBuilder.Entity("project.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("project.Models.Booking", b =>
                {
                    b.HasOne("project.Models.TravelPackage", "TravelPackage")
                        .WithMany("Bookings")
                        .HasForeignKey("TravelPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("project.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelPackage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("project.Models.CartItem", b =>
                {
                    b.HasOne("project.Models.TravelPackage", "TravelPackage")
                        .WithMany("CartItems")
                        .HasForeignKey("TravelPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("project.Models.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TravelPackage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("project.Models.TravelPackage", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("project.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
